id: I6DB9BBB2
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T15:06:59.770986'
last_modified: '2022-05-27T15:06:59.770998'
parser: null
source_metadata:
  title: Khaḍgaviṣāṇasūtra
  language: pgd
  base:
    f265F:
      title: Complete text
      base_file: f265F.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
